### PR TITLE
test: model-search schema

### PR DESCRIPTION
**Pull request by mcdurdin**
Adds schema for model-search, rearrange files slightly, and then test against the schema.

### CODE REVIEW

**Comment by mcdurdin** [comment]
> Is this possible to test against the staging server at present?

This chain of PRs will merge into `staging` which will then be deployed to the staging server.

**Comment by jahorton** [comment]
So... no, it's not possible to actually test-run this against the API.

I was hoping to more thoroughly check that this area wasn't affected by the refactoring and shift from MySQL to MSSQL as part of the review.

**Comment by mcdurdin** [comment]
> So... no, it's not possible to actually test-run this against the API.

Sure, just run it locally (probably simpler to run on Windows though). Once you have SQL Server Developer Edition installed (requires FullText support, hence Developer Edition not Express Edition), then you can run on your local machine fairly easily. I am working on the README to clarify the steps for setup.

**Comment by mcdurdin** [comment]
> I was hoping to more thoroughly check that this area wasn't affected by the refactoring and shift from MySQL to MSSQL as part of the review.

Once this merges, I will be running more tests against staging -- manual and automated, and then I would encourage you to open issues against it then. It might be less painful than trying to setup your own local environment (Windows only), although admittedly it is a one-time cost.

**Comment by jahorton** [comment]
And now a more confident LGTM; just checked the queries against the staging server.

**Pull request merged**
